# Generated by Django 5.2.12 on 2026-03-10 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('records', models.IntegerField(default=0)),
                ('archivedDate', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'archived_records',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('municipalities', models.IntegerField(default=0)),
                ('barangays', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=32)),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(blank=True, max_length=255)),
                ('module', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'system_logs',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barangays', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=32)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities_set', to='core.province')),
            ],
            options={
                'db_table': 'municipalities',
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('officer', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_records', to='core.municipality')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_records', to='core.province')),
            ],
            options={
                'db_table': 'compliance_records',
            },
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('population', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=32)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangays_set', to='core.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangays_set', to='core.province')),
            ],
            options={
                'db_table': 'barangays',
            },
        ),
    ]
