# Generated by Django 5.2.12 on 2026-03-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerecord',
            name='approvalDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='hardCopyAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='planEndYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='planStartYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='resolutionNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='softCopyUrl',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
