# Generated by Django 4.2 on 2026-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_compliancerecord_approvaldate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerecord',
            name='integratedShelterPlan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='riskInformed',
            field=models.BooleanField(default=False),
        ),
    ]
