# Generated by Django 4.2 on 2026-03-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_compliancerecord_integratedshelterplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(blank=True, max_length=255, null=True)),
                ('subclass', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('meansOfVerification', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'definition_status',
            },
        ),
        migrations.CreateModel(
            name='AnnexPdpfpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('incomeClassification', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('startYear', models.IntegerField(blank=True, null=True)),
                ('endYear', models.IntegerField(blank=True, null=True)),
                ('resolutionApprovingPlan', models.CharField(blank=True, max_length=255, null=True)),
                ('yearApproved', models.IntegerField(blank=True, null=True)),
                ('yearAdopted', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('technicalAssistance', models.TextField(blank=True, null=True)),
                ('supportFromOtherInstitutions', models.TextField(blank=True, null=True)),
                ('withLocalShelterPlan', models.CharField(blank=True, max_length=100, null=True)),
                ('institutions', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'annex_pdpfp_status',
                'unique_together': {('province', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AnnexClupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityMunicipality', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('planningStartYear', models.IntegerField(blank=True, null=True)),
                ('planningEndYear', models.IntegerField(blank=True, null=True)),
                ('resolutionNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('clupStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('prePhase', models.BooleanField(default=False)),
                ('phase1', models.BooleanField(default=False)),
                ('phase2', models.BooleanField(default=False)),
                ('phase3', models.BooleanField(default=False)),
                ('phase4', models.BooleanField(default=False)),
                ('phase5', models.BooleanField(default=False)),
                ('currentProgress', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'annex_clup_status',
                'unique_together': {('cityMunicipality', 'province')},
            },
        ),
    ]
